all:
	gcc ./1/hash.c ./1/main.c -o ./1/q1.o
	gcc ./2/hash.c ./2/main.c -o ./2/q2.o
	gcc ./3/heap.c ./3/main.c -o ./3/q3.o
	gcc ./4/heap.c ./4/main.c -o ./4/q4.o
	
q1:
	gcc ./1/hash.c ./1/main.c -o ./1/q1.o
	
q2:
	gcc ./2/hash.c ./2/main.c -o ./2/q2.o

q3:
	gcc ./3/heap.c ./3/main.c -o ./3/q3.o
	
q4:
	gcc ./4/heap.c ./4/main.c -o ./4/q4.o
